const whiteList = [
  'REACT_APP_FIREBASE_API_KEY',
  'REACT_APP_FIREBASE_AUTH_DOMAIN',
  'REACT_APP_FIREBASE_DATABASE_URL',
  'REACT_APP_FIREBASE_PROJECT_ID',
  'REACT_APP_HOST',
  'REACT_APP_PLAID_CLIENT_ID',
  'REACT_APP_PLAID_PUBLIC_KEY',
  'REACT_APP_PLAID_ENV',
  'REACT_APP_WEBHOOK',
];

module.exports = whiteList;
